spring:
    datasource:
        url: jdbc:postgresql://localhost:5434/product
        username: postgres
        password: postgres

    flyway:
        enabled: true
        locations: classpath:db/migration

api:
    security:
        token:
            secret: ${JWT_SECRET:my-secret-key}
